from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(True)


        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)

        self.centralwidget.setObjectName("centralwidget")
        self.buttonOpenFile = QtWidgets.QPushButton(self.centralwidget)
        self.buttonOpenFile.setGeometry(QtCore.QRect(90, 20, 47, 47))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonOpenFile.sizePolicy().hasHeightForWidth())
        self.buttonOpenFile.setSizePolicy(sizePolicy)


        self.buttonOpenFile.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/load.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonOpenFile.setIcon(icon1)
        self.buttonOpenFile.setIconSize(QtCore.QSize(35, 35))
        self.buttonOpenFile.setObjectName("buttonOpenFile")
        self.buttonSaveFile = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSaveFile.setGeometry(QtCore.QRect(137, 20, 47, 47))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSaveFile.sizePolicy().hasHeightForWidth())
        self.buttonSaveFile.setSizePolicy(sizePolicy)


        self.buttonSaveFile.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonSaveFile.setIcon(icon2)
        self.buttonSaveFile.setIconSize(QtCore.QSize(37, 37))
        self.buttonSaveFile.setObjectName("buttonSaveFile")
        self.buttonCrop = QtWidgets.QPushButton(self.centralwidget)
        self.buttonCrop.setGeometry(QtCore.QRect(20, 270, 47, 47))


        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/crop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonCrop.setIcon(icon3)
        self.buttonCrop.setIconSize(QtCore.QSize(40, 40))
        self.buttonCrop.setObjectName("buttonCrop")
        self.buttonUnDo = QtWidgets.QPushButton(self.centralwidget)
        self.buttonUnDo.setGeometry(QtCore.QRect(184, 20, 47, 47))


        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonUnDo.setIcon(icon4)
        self.buttonUnDo.setIconSize(QtCore.QSize(37, 37))
        self.buttonUnDo.setObjectName("buttonUnDo")
        self.buttonReDo = QtWidgets.QPushButton(self.centralwidget)
        self.buttonReDo.setGeometry(QtCore.QRect(231, 20, 47, 47))

        self.buttonReDo.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonReDo.setIcon(icon5)
        self.buttonReDo.setIconSize(QtCore.QSize(37, 37))
        self.buttonReDo.setObjectName("buttonReDo")
        self.buttonText = QtWidgets.QPushButton(self.centralwidget)
        self.buttonText.setGeometry(QtCore.QRect(20, 90, 47, 47))


        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/text-formatting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonText.setIcon(icon6)
        self.buttonText.setIconSize(QtCore.QSize(40, 40))
        self.buttonText.setObjectName("buttonText")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(90, 80, 191, 301))

        self.stackedWidget.setObjectName("stackedWidget")
        self.blankPage = QtWidgets.QWidget()
        self.blankPage.setObjectName("blankPage")
        self.stackedWidget.addWidget(self.blankPage)
        self.colorSettings = QtWidgets.QWidget()
        self.colorSettings.setObjectName("colorSettings")
        self.horizontalSliderHue = QtWidgets.QSlider(self.colorSettings)
        self.horizontalSliderHue.setGeometry(QtCore.QRect(0, 30, 151, 22))
        self.horizontalSliderHue.setMaximumSize(QtCore.QSize(16777215, 16777214))

        self.horizontalSliderHue.setMaximum(255)
        self.horizontalSliderHue.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderHue.setObjectName("horizontalSliderHue")
        self.horizontalSliderBrightness = QtWidgets.QSlider(self.colorSettings)
        self.horizontalSliderBrightness.setGeometry(QtCore.QRect(0, 150, 151, 22))

        self.horizontalSliderBrightness.setMinimum(-127)
        self.horizontalSliderBrightness.setMaximum(127)
        self.horizontalSliderBrightness.setProperty("value", 0)
        self.horizontalSliderBrightness.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderBrightness.setObjectName("horizontalSliderBrightness")
        self.labelTextHue = QtWidgets.QLabel(self.colorSettings)
        self.labelTextHue.setGeometry(QtCore.QRect(0, 10, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTextHue.setFont(font)


        self.labelTextHue.setObjectName("labelTextHue")
        self.labelTextSight = QtWidgets.QLabel(self.colorSettings)
        self.labelTextSight.setGeometry(QtCore.QRect(0, 70, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTextSight.setFont(font)

        self.labelTextSight.setObjectName("labelTextSight")
        self.horizontalSliderContrast = QtWidgets.QSlider(self.colorSettings)
        self.horizontalSliderContrast.setGeometry(QtCore.QRect(0, 90, 151, 22))

        self.horizontalSliderContrast.setMinimum(0)
        self.horizontalSliderContrast.setMaximum(100)
        self.horizontalSliderContrast.setProperty("value", 50)
        self.horizontalSliderContrast.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderContrast.setObjectName("horizontalSliderContrast")
        self.labelTextBrightness = QtWidgets.QLabel(self.colorSettings)
        self.labelTextBrightness.setGeometry(QtCore.QRect(0, 130, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTextBrightness.setFont(font)

        self.labelTextBrightness.setObjectName("labelTextBrightness")
        self.comboBoxFilters = QtWidgets.QComboBox(self.colorSettings)
        self.comboBoxFilters.setGeometry(QtCore.QRect(0, 210, 120, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBoxFilters.setFont(font)
        self.comboBoxFilters.setObjectName("comboBoxFilters")
        self.comboBoxFilters.addItem("")
        self.comboBoxFilters.addItem("")
        self.comboBoxFilters.addItem("")
        self.comboBoxFilters.addItem("")
        self.comboBoxFilters.addItem("")
        self.labelTextFilters = QtWidgets.QLabel(self.colorSettings)
        self.labelTextFilters.setGeometry(QtCore.QRect(0, 190, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTextFilters.setFont(font)

        self.labelTextFilters.setObjectName("labelTextFilters")
        self.stackedWidget.addWidget(self.colorSettings)
        self.textSettings = QtWidgets.QWidget()
        self.textSettings.setObjectName("textSettings")
        self.labelTextText = QtWidgets.QLabel(self.textSettings)
        self.labelTextText.setGeometry(QtCore.QRect(0, 10, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTextText.setFont(font)

        self.labelTextText.setObjectName("labelTextText")
        self.lineEditText = QtWidgets.QLineEdit(self.textSettings)
        self.lineEditText.setGeometry(QtCore.QRect(0, 30, 161, 22))


        self.lineEditText.setObjectName("lineEditText")
        self.labelTextTextSizeText = QtWidgets.QLabel(self.textSettings)
        self.labelTextTextSizeText.setGeometry(QtCore.QRect(0, 70, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTextTextSizeText.setFont(font)

        self.labelTextTextSizeText.setObjectName("labelTextTextSizeText")
        self.comboTextSize = QtWidgets.QComboBox(self.textSettings)
        self.comboTextSize.setGeometry(QtCore.QRect(0, 89, 120, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboTextSize.setFont(font)
        self.comboTextSize.setObjectName("comboTextSize")
        self.comboTextSize.addItem("")
        self.comboTextSize.addItem("")
        self.comboTextSize.addItem("")
        self.comboTextSize.addItem("")
        self.comboTextSize.addItem("")
        self.comboTextSize.addItem("")
        self.comboTextSize.addItem("")
        self.comboTextSize.addItem("")
        self.labelTextTextColorText = QtWidgets.QLabel(self.textSettings)
        self.labelTextTextColorText.setGeometry(QtCore.QRect(0, 130, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTextTextColorText.setFont(font)

        self.labelTextTextColorText.setObjectName("labelTextTextColorText")
        self.buttonChooseColor = QtWidgets.QPushButton(self.textSettings)
        self.buttonChooseColor.setGeometry(QtCore.QRect(0, 150, 21, 21))


        self.buttonChooseColor.setObjectName("buttonChooseColor")
        self.stackedWidget.addWidget(self.textSettings)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.buttonFlipHoriz = QtWidgets.QPushButton(self.page)
        self.buttonFlipHoriz.setGeometry(QtCore.QRect(0, 10, 47, 47))

        self.buttonFlipHoriz.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/flip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonFlipHoriz.setIcon(icon7)
        self.buttonFlipHoriz.setIconSize(QtCore.QSize(37, 37))
        self.buttonFlipHoriz.setObjectName("buttonFlipHoriz")
        self.buttonFlipVertic = QtWidgets.QPushButton(self.page)
        self.buttonFlipVertic.setGeometry(QtCore.QRect(47, 10, 47, 47))

        self.buttonFlipVertic.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/flip (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonFlipVertic.setIcon(icon8)
        self.buttonFlipVertic.setIconSize(QtCore.QSize(37, 37))
        self.buttonFlipVertic.setObjectName("buttonFlipVertic")
        self.horizontalSliderRotation = QtWidgets.QSlider(self.page)
        self.horizontalSliderRotation.setGeometry(QtCore.QRect(0, 90, 151, 22))

        self.horizontalSliderRotation.setMaximum(45)
        self.horizontalSliderRotation.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderRotation.setObjectName("horizontalSliderRotation")
        self.labelTextRotation = QtWidgets.QLabel(self.page)
        self.labelTextRotation.setGeometry(QtCore.QRect(0, 70, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTextRotation.setFont(font)


        self.labelTextRotation.setObjectName("labelTextRotation")
        self.buttonRotate90 = QtWidgets.QPushButton(self.page)
        self.buttonRotate90.setGeometry(QtCore.QRect(94, 10, 47, 47))

        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/rotate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonRotate90.setIcon(icon9)
        self.buttonRotate90.setIconSize(QtCore.QSize(35, 35))
        self.buttonRotate90.setObjectName("buttonRotate90")
        self.stackedWidget.addWidget(self.page)
        self.buttonColor = QtWidgets.QPushButton(self.centralwidget)
        self.buttonColor.setGeometry(QtCore.QRect(20, 150, 47, 47))

        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonColor.setIcon(icon10)
        self.buttonColor.setIconSize(QtCore.QSize(40, 40))
        self.buttonColor.setObjectName("buttonColor")
        self.buttonRotationMenu = QtWidgets.QPushButton(self.centralwidget)
        self.buttonRotationMenu.setGeometry(QtCore.QRect(20, 210, 47, 47))

        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/rotation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonRotationMenu.setIcon(icon11)
        self.buttonRotationMenu.setIconSize(QtCore.QSize(40, 40))
        self.buttonRotationMenu.setObjectName("buttonRotation")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1280, 720))

        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.buttonOpenFile.raise_()
        self.buttonSaveFile.raise_()
        self.buttonCrop.raise_()
        self.buttonUnDo.raise_()
        self.buttonReDo.raise_()
        self.buttonText.raise_()
        self.stackedWidget.raise_()
        self.buttonColor.raise_()
        self.buttonRotationMenu.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PhotoEditor"))
        self.labelTextHue.setText(_translate("MainWindow", "Hue"))
        self.labelTextSight.setText(_translate("MainWindow", "Contrast"))
        self.labelTextBrightness.setText(_translate("MainWindow", "Brightness"))
        self.comboBoxFilters.setItemText(0, _translate("MainWindow", "None"))
        self.comboBoxFilters.setItemText(1, _translate("MainWindow", "Sepia"))
        self.comboBoxFilters.setItemText(2, _translate("MainWindow", "Invert"))
        self.comboBoxFilters.setItemText(3, _translate("MainWindow", "Gray"))
        self.comboBoxFilters.setItemText(4, _translate("MainWindow", "Sharpen"))
        self.labelTextFilters.setText(_translate("MainWindow", "Filters"))
        self.labelTextText.setText(_translate("MainWindow", "Text"))
        self.labelTextTextSizeText.setText(_translate("MainWindow", "Text Size"))
        self.comboTextSize.setItemText(0, _translate("MainWindow", "1"))
        self.comboTextSize.setItemText(1, _translate("MainWindow", "2"))
        self.comboTextSize.setItemText(2, _translate("MainWindow", "3"))
        self.comboTextSize.setItemText(3, _translate("MainWindow", "4"))
        self.comboTextSize.setItemText(4, _translate("MainWindow", "5"))
        self.comboTextSize.setItemText(5, _translate("MainWindow", "6"))
        self.comboTextSize.setItemText(6, _translate("MainWindow", "7"))
        self.comboTextSize.setItemText(7, _translate("MainWindow", "8"))
        self.labelTextTextColorText.setText(_translate("MainWindow", "Text Color"))
        self.labelTextRotation.setText(_translate("MainWindow", "Rotation Degrees"))